### ISSUE TITLE
file endpoints giving 502 bad gateway error

### ISSUE THREAD

**Issue by elijahlowe** [CancerDataAggregator/cda-python#40] opened 2021-08-05 19:45 UTC
When trying the following query (related to the endpoint, not the query condition):

```
**dcat = Q('ResearchSubject.Specimen.File.data_category = "Somatic Structural Variation"')
rcat = dcat.run()**
```

```
---------------------------------------------------------------------------
ServiceException                          Traceback (most recent call last)
<ipython-input-27-f0ea2231bf04> in <module>
      1 dcat = Q('ResearchSubject.Specimen.File.data_category = "Somatic Structural Variation"')
----> 2 rcat = dcat.run()

~/Desktop/cda-python/cdapython.py in run(self, offset, limit, version, host, dry_run)
     87             if dry_run:
     88                 return api_response
---> 89             return get_query_result(api_instance, api_response.query_id, offset, limit)
     90 
     91     def And(self, right: "Q"):

~/Desktop/cda-python/cdapython.py in get_query_result(api_instance, query_id, offset, limit)
     41 def get_query_result(api_instance, query_id, offset, limit):
     42     while True:
---> 43         response = api_instance.query(id=query_id, offset=offset, limit=limit)
     44         if response.total_row_count is not None:
     45             return Result(response, query_id, offset, limit, api_instance)

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in __call__(self, *args, **kwargs)
    769 
    770         """
--> 771         return self.callable(self, *args, **kwargs)
    772 
    773     def call_with_http_info(self, **kwargs):

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api/query_api.py in __query(self, id, **kwargs)
    356             kwargs['id'] = \
    357                 id
--> 358             return self.call_with_http_info(**kwargs)
    359 
    360         self.query = _Endpoint(

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in call_with_http_info(self, **kwargs)
    831             params['header']['Content-Type'] = header_list
    832 
--> 833         return self.api_client.call_api(
    834             self.settings['endpoint_path'], self.settings['http_method'],
    835             params['path'],

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, async_req, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _check_type)
    406         """
    407         if not async_req:
--> 408             return self.__call_api(resource_path, method,
    409                                    path_params, query_params, header_params,
    410                                    body, post_params, files,

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _check_type)
    200         except ApiException as e:
    201             e.body = e.body.decode('utf-8')
--> 202             raise e
    203 
    204         self.last_response = response_data

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _check_type)
    193         try:
    194             # perform request and return response
--> 195             response_data = self.request(
    196                 method, url, query_params=query_params, headers=header_params,
    197                 post_params=post_params, body=body,

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/api_client.py in request(self, method, url, query_params, headers, post_params, body, _preload_content, _request_timeout)
    432         """Makes the HTTP request using RESTClient."""
    433         if method == "GET":
--> 434             return self.rest_client.GET(url,
    435                                         query_params=query_params,
    436                                         _preload_content=_preload_content,

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/rest.py in GET(self, url, headers, query_params, _preload_content, _request_timeout)
    229     def GET(self, url, headers=None, query_params=None, _preload_content=True,
    230             _request_timeout=None):
--> 231         return self.request("GET", url,
    232                             headers=headers,
    233                             _preload_content=_preload_content,

~/opt/miniconda3/envs/cda/lib/python3.9/site-packages/cda_client/rest.py in request(self, method, url, query_params, headers, body, post_params, _preload_content, _request_timeout)
    221 
    222             if 500 <= r.status <= 599:
--> 223                 raise ServiceException(http_resp=r)
    224 
    225             raise ApiException(http_resp=r)

ServiceException: (502)
Reason: Bad Gateway
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/html; charset=UTF-8', 'Referrer-Policy': 'no-referrer', 'Content-Length': '332', 'Date': 'Thu, 05 Aug 2021 19:10:32 GMT', 'Alt-Svc': 'clear'})
HTTP response body: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

```
The same goes for `q = Q('ResearchSubject.Specimen.File.file_format = "mzML"')` 

However, when running the queries in bigquery, the work.
```
SELECT v3.* 
FROM gdc-bq-sample.cda_mvp.v3 AS v3, UNNEST(ResearchSubject) AS _ResearchSubject, UNNEST(_ResearchSubject.Specimen) AS _Specimen, UNNEST(_Specimen.File) AS _File 
WHERE (_File.data_category = 'Somatic Structural Variation')
```

**Comment by fkaufman-asym** [comment] 2021-08-13 19:27
It looks like the 502 is being caused by a timeout by long running query.  We are going to build an endpoint that we can see if a query is still running and possibly poll it to support an asynchronous return of data.

**Comment by pshapiro4broad** [comment] 2021-08-17 17:18
The query endpoint already is asynchronous and supports polling. If a query is still running, it will return immediately with an empty result.
https://github.com/CancerDataAggregator/cda-service/blob/master/src/main/java/bio/terra/cda/app/service/QueryService.java#L127

The cda-python code polls for the query response in `while` loop.
https://github.com/CancerDataAggregator/cda-python/blob/main/cdapython.py#L43

The polling loop doesn't sleep between polls, possibly that's causing a problem by making too many requests too fast to the endpoint.

**Comment by dionboles-asym** [comment] 2021-09-02 16:11
The error is because of the cda-service timeouts in the bigquery request the query is longer then 10s then bigquery will stop the request the quick fix is to add this code to startQuery 
`    queryJob = queryJob.waitFor(RetryOption.initialRetryDelay(Duration.ofSeconds(1)), RetryOption.totalTimeout(Duration.ofMinutes(2)));
`
this is a quick fix.

**Comment by ACharbonneau** [comment] 2022-07-07 17:33
This was fixed with the long queries fix

**Closed by ACharbonneau** 2022-07-07 17:33 UTC
Labels: bug, Release 2.1
